# Generated by Django 5.2.10 on 2026-01-23 13:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntentoExamen',
            fields=[
                ('id_intento', models.AutoField(primary_key=True, serialize=False)),
                ('estudiante_id', models.IntegerField(db_index=True, help_text='ID del estudiante desde auth-service')),
                ('estudiante_nombre', models.CharField(help_text='Nombre del estudiante (desnormalizado)', max_length=200)),
                ('estudiante_cedula', models.CharField(max_length=10)),
                ('examen_id', models.IntegerField(db_index=True, help_text='ID del examen desde exam-service')),
                ('examen_titulo', models.CharField(help_text='Título del examen (desnormalizado)', max_length=200)),
                ('horario_id', models.IntegerField(blank=True, help_text='ID del horario asignado', null=True)),
                ('numero_intento', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('estado', models.CharField(choices=[('INICIADO', 'Iniciado'), ('EN_PROGRESO', 'En Progreso'), ('COMPLETADO', 'Completado'), ('EXPULSADO', 'Expulsado'), ('ABANDONADO', 'Abandonado'), ('TIEMPO_AGOTADO', 'Tiempo Agotado')], default='INICIADO', max_length=20)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('fecha_limite', models.DateTimeField(help_text='Fecha y hora límite para completar el examen')),
                ('tiempo_total', models.IntegerField(default=0, help_text='Tiempo total en segundos')),
                ('calificacion_final', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('puntaje_obtenido', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('puntaje_total', models.DecimalField(decimal_places=2, help_text='Puntaje total del examen', max_digits=5)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('validacion_facial_completada', models.BooleanField(default=False)),
                ('camara_activada', models.BooleanField(default=False)),
                ('preguntas_totales', models.IntegerField(default=0)),
                ('preguntas_respondidas', models.IntegerField(default=0)),
                ('preguntas_correctas', models.IntegerField(default=0)),
                ('preguntas_incorrectas', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Intento de Examen',
                'verbose_name_plural': 'Intentos de Examen',
                'db_table': 'intentos_examen',
                'ordering': ['-fecha_inicio'],
                'indexes': [models.Index(fields=['estudiante_id', 'examen_id'], name='intentos_ex_estudia_640917_idx'), models.Index(fields=['examen_id', 'estado'], name='intentos_ex_examen__d06964_idx'), models.Index(fields=['fecha_inicio', 'estado'], name='intentos_ex_fecha_i_c5d0a4_idx'), models.Index(fields=['estudiante_id', 'estado'], name='intentos_ex_estudia_ae3c39_idx')],
                'unique_together': {('estudiante_id', 'examen_id', 'numero_intento')},
            },
        ),
        migrations.CreateModel(
            name='RespuestaEstudiante',
            fields=[
                ('id_respuesta', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta_id', models.IntegerField(db_index=True, help_text='ID de la pregunta desde exam-service')),
                ('pregunta_enunciado', models.TextField(help_text='Enunciado de la pregunta (desnormalizado)')),
                ('pregunta_ponderacion', models.DecimalField(decimal_places=2, help_text='Ponderación de la pregunta', max_digits=5)),
                ('opcion_id', models.IntegerField(blank=True, help_text='ID de la opción seleccionada', null=True)),
                ('opciones_ids', models.JSONField(blank=True, default=list, help_text='IDs de opciones seleccionadas (para selección múltiple)')),
                ('opcion_texto', models.TextField(blank=True, help_text='Texto de la opción seleccionada (desnormalizado)')),
                ('es_correcta', models.BooleanField(default=False)),
                ('puntaje_obtenido', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tiempo_respuesta', models.IntegerField(default=0, help_text='Tiempo en segundos que tardó en responder')),
                ('numero_orden', models.IntegerField(default=0, help_text='Orden en que se respondió la pregunta')),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('intento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='analisis.intentoexamen')),
            ],
            options={
                'verbose_name': 'Respuesta de Estudiante',
                'verbose_name_plural': 'Respuestas de Estudiante',
                'db_table': 'respuestas_estudiante',
                'ordering': ['intento', 'numero_orden'],
                'indexes': [models.Index(fields=['intento', 'pregunta_id'], name='respuestas__intento_3982e8_idx'), models.Index(fields=['intento', 'es_correcta'], name='respuestas__intento_f9141e_idx')],
                'unique_together': {('intento', 'pregunta_id')},
            },
        ),
    ]
