# Generated by Django 5.2.10 on 2026-01-23 13:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id_examen', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('docente_id', models.IntegerField(db_index=True, help_text='ID del docente desde auth-service')),
                ('docente_nombre', models.CharField(help_text='Nombre del docente (desnormalizado para performance)', max_length=200)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PUBLICADO', 'Publicado'), ('ACTIVO', 'Activo'), ('FINALIZADO', 'Finalizado'), ('ARCHIVADO', 'Archivado')], default='BORRADOR', max_length=20)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('duracion', models.IntegerField(help_text='Duración en minutos', validators=[django.core.validators.MinValueValidator(1)])),
                ('instrucciones', models.TextField(blank=True)),
                ('intentos_permitidos', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('mostrar_respuestas', models.BooleanField(default=False, help_text='Mostrar respuestas correctas al finalizar')),
                ('aleatorizar_preguntas', models.BooleanField(default=False)),
                ('requiere_camara', models.BooleanField(default=True, help_text='Requiere monitoreo por cámara')),
                ('puntaje_total', models.DecimalField(decimal_places=2, default=0, help_text='Puntaje total del examen (suma de ponderaciones)', max_digits=5)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Examen',
                'verbose_name_plural': 'Exámenes',
                'db_table': 'examenes',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['docente_id', 'estado'], name='examenes_docente_55c7f2_idx'), models.Index(fields=['fecha_inicio', 'fecha_fin'], name='examenes_fecha_i_05530f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id_pregunta', models.AutoField(primary_key=True, serialize=False)),
                ('enunciado', models.TextField()),
                ('tipo', models.CharField(choices=[('OPCION_MULTIPLE', 'Opción Múltiple'), ('VERDADERO_FALSO', 'Verdadero/Falso'), ('SELECCION_MULTIPLE', 'Selección Múltiple')], default='OPCION_MULTIPLE', max_length=20)),
                ('ponderacion', models.DecimalField(decimal_places=2, default=1.0, help_text='Valor de la pregunta en puntos', max_digits=5, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('orden', models.IntegerField(default=0, help_text='Orden de aparición en el examen')),
                ('imagen', models.ImageField(blank=True, help_text='Imagen asociada a la pregunta', null=True, upload_to='preguntas/')),
                ('explicacion', models.TextField(blank=True, help_text='Explicación de la respuesta correcta')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='examenes.examen')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
                'db_table': 'preguntas',
                'ordering': ['examen', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='OpcionRespuesta',
            fields=[
                ('id_opcion', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.TextField()),
                ('es_correcta', models.BooleanField(default=False)),
                ('orden', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='examenes.pregunta')),
            ],
            options={
                'verbose_name': 'Opción de Respuesta',
                'verbose_name_plural': 'Opciones de Respuesta',
                'db_table': 'opciones_respuesta',
                'ordering': ['pregunta', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id_horario', models.AutoField(primary_key=True, serialize=False)),
                ('grupo', models.CharField(blank=True, help_text='Nombre del grupo o paralelo', max_length=100)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('aula', models.CharField(blank=True, max_length=50)),
                ('cupos_maximos', models.IntegerField(blank=True, help_text='Número máximo de estudiantes para este horario', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('estudiantes_ids', models.JSONField(blank=True, default=list, help_text='Lista de IDs de estudiantes asignados a este horario')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='examenes.examen')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'db_table': 'horarios',
                'ordering': ['fecha', 'hora_inicio'],
                'indexes': [models.Index(fields=['examen', 'fecha'], name='horarios_examen__188ff5_idx'), models.Index(fields=['fecha', 'hora_inicio'], name='horarios_fecha_3ad1e1_idx')],
                'unique_together': {('examen', 'grupo', 'fecha', 'hora_inicio')},
            },
        ),
        migrations.AddIndex(
            model_name='pregunta',
            index=models.Index(fields=['examen', 'orden'], name='preguntas_examen__5cc672_idx'),
        ),
        migrations.AddIndex(
            model_name='opcionrespuesta',
            index=models.Index(fields=['pregunta', 'es_correcta'], name='opciones_re_pregunt_535ffd_idx'),
        ),
    ]
