# Generated by Django 5.2.10 on 2026-01-25 23:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examen',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.AlterModelOptions(
            name='horario',
            options={'ordering': ['fecha', 'hora_inicio']},
        ),
        migrations.AlterModelOptions(
            name='opcionrespuesta',
            options={'ordering': ['pregunta', 'orden']},
        ),
        migrations.AlterModelOptions(
            name='pregunta',
            options={'ordering': ['examen', 'orden']},
        ),
        migrations.RemoveIndex(
            model_name='examen',
            name='examenes_docente_55c7f2_idx',
        ),
        migrations.RemoveIndex(
            model_name='examen',
            name='examenes_fecha_i_05530f_idx',
        ),
        migrations.RemoveIndex(
            model_name='horario',
            name='horarios_examen__188ff5_idx',
        ),
        migrations.RemoveIndex(
            model_name='horario',
            name='horarios_fecha_3ad1e1_idx',
        ),
        migrations.RemoveIndex(
            model_name='opcionrespuesta',
            name='opciones_re_pregunt_535ffd_idx',
        ),
        migrations.RemoveIndex(
            model_name='pregunta',
            name='preguntas_examen__5cc672_idx',
        ),
        migrations.AlterUniqueTogether(
            name='horario',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='fecha_actualizacion',
        ),
        migrations.AlterField(
            model_name='examen',
            name='docente_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='examen',
            name='docente_nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='examen',
            name='duracion',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='examen',
            name='mostrar_respuestas',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='examen',
            name='puntaje_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='examen',
            name='requiere_camara',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='horario',
            name='cupos_maximos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='horario',
            name='estudiantes_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='horario',
            name='grupo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='explicacion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='preguntas/'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='orden',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='ponderacion',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
