# Generated by Django 5.2.10 on 2026-02-05 05:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0002_alter_examen_options_alter_horario_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id_materia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('codigo', models.CharField(blank=True, db_index=True, max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'materias',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='examen',
            name='aleatorizar_opciones',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='examen',
            name='ia_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='examen',
            name='idioma',
            field=models.CharField(choices=[('ES', 'Español'), ('EN', 'English'), ('PT', 'Português')], default='ES', max_length=5),
        ),
        migrations.AddField(
            model_name='examen',
            name='nivel',
            field=models.CharField(choices=[('BASICO', 'Básico'), ('INTERMEDIO', 'Intermedio'), ('AVANZADO', 'Avanzado')], default='INTERMEDIO', max_length=20),
        ),
        migrations.AddField(
            model_name='examen',
            name='origen',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('IA', 'IA'), ('MIXTO', 'Mixto')], default='MANUAL', max_length=10),
        ),
        migrations.AddField(
            model_name='examen',
            name='parametros_generacion',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='examen',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='opcionrespuesta',
            name='clave',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='dificultad',
            field=models.CharField(choices=[('FACIL', 'Fácil'), ('MEDIA', 'Media'), ('DIFICIL', 'Difícil')], default='MEDIA', max_length=10),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='ia_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='respuesta_texto',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='resultado_aprendizaje',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='tema',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='examen',
            name='duracion',
            field=models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='examen',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('GENERANDO', 'Generando (IA)'), ('PUBLICADO', 'Publicado'), ('ACTIVO', 'Activo'), ('FINALIZADO', 'Finalizado'), ('ARCHIVADO', 'Archivado'), ('ERROR_GENERACION', 'Error generación (IA)')], default='BORRADOR', max_length=30),
        ),
        migrations.AlterField(
            model_name='examen',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examen',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examen',
            name='puntaje_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='ponderacion',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='tipo',
            field=models.CharField(choices=[('OPCION_MULTIPLE', 'Opción Múltiple'), ('VERDADERO_FALSO', 'Verdadero/Falso'), ('SELECCION_MULTIPLE', 'Selección Múltiple'), ('RESPUESTA_CORTA', 'Respuesta corta')], default='OPCION_MULTIPLE', max_length=30),
        ),
        migrations.AddField(
            model_name='examen',
            name='materia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='examenes', to='examenes.materia'),
        ),
        migrations.AddIndex(
            model_name='examen',
            index=models.Index(fields=['materia', 'estado'], name='examenes_materia_d34811_idx'),
        ),
        migrations.AddIndex(
            model_name='examen',
            index=models.Index(fields=['docente_id', 'estado'], name='examenes_docente_55c7f2_idx'),
        ),
    ]
