# Generated by Django 5.2.10 on 2026-02-05 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0003_materia_examen_aleatorizar_opciones_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='examen',
            name='examenes_materia_d34811_idx',
        ),
        migrations.RemoveIndex(
            model_name='examen',
            name='examenes_docente_55c7f2_idx',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='imagen',
        ),
    ]
