# Generated by Django 5.2.10 on 2026-01-29 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='reporte_padre_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
