# Generated by Django 5.2.10 on 2026-01-23 14:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertencia',
            fields=[
                ('id_advertencia', models.AutoField(primary_key=True, serialize=False)),
                ('intento_id', models.IntegerField(db_index=True, help_text='ID del intento del examen')),
                ('estudiante_id', models.IntegerField(db_index=True)),
                ('estudiante_nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('AUSENCIA', 'Estudiante no detectado'), ('MULTIPLES_PERSONAS', 'Múltiples personas detectadas'), ('MIRADA_DESVIADA', 'Mirada fuera de pantalla'), ('OBJETO_NO_AUTORIZADO', 'Objeto no autorizado'), ('CAMBIO_VENTANA', 'Cambio de ventana'), ('PERDIDA_CONEXION', 'Pérdida de conexión'), ('CAMARA_BLOQUEADA', 'Cámara bloqueada'), ('COMPORTAMIENTO_SOSPECHOSO', 'Comportamiento sospechoso')], max_length=30)),
                ('nivel', models.CharField(choices=[('LEVE', 'Leve'), ('MODERADO', 'Moderado'), ('GRAVE', 'Grave')], default='MODERADO', max_length=10)),
                ('descripcion', models.TextField(blank=True)),
                ('confianza', models.DecimalField(decimal_places=2, help_text='Nivel de confianza del evento', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('evidencia_url', models.URLField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('resuelta', models.BooleanField(default=False)),
                ('notas_resolucion', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Advertencia',
                'verbose_name_plural': 'Advertencias',
                'db_table': 'advertencias',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionMonitoreo',
            fields=[
                ('id_config', models.AutoField(primary_key=True, serialize=False)),
                ('examen_id', models.IntegerField(help_text='ID del examen', unique=True)),
                ('max_advertencias', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('umbral_confianza_minimo', models.DecimalField(decimal_places=2, default=70, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('tiempo_sin_rostro_max', models.IntegerField(default=10, help_text='Segundos máximos sin rostro')),
                ('tiempo_mirada_desviada_max', models.IntegerField(default=15, help_text='Segundos máximos con mirada desviada')),
                ('permitir_multiples_personas', models.BooleanField(default=False)),
                ('captura_periodica_frames', models.BooleanField(default=True)),
                ('intervalo_captura_segundos', models.IntegerField(default=30)),
                ('requiere_pantalla_completa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Monitoreo',
                'verbose_name_plural': 'Configuraciones de Monitoreo',
                'db_table': 'configuracion_monitoreo',
            },
        ),
        migrations.CreateModel(
            name='RegistroMonitoreo',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('intento_id', models.IntegerField(db_index=True, help_text='ID del intento del examen', unique=True)),
                ('estudiante_id', models.IntegerField(db_index=True)),
                ('tipo_evento', models.CharField(choices=[('INICIO_SESION', 'Inicio de sesión'), ('FRAME_PROCESADO', 'Frame procesado'), ('ROSTRO_DETECTADO', 'Rostro detectado'), ('SIN_ROSTRO', 'Sin rostro detectado'), ('MULTIPLES_ROSTROS', 'Múltiples rostros detectados'), ('MIRADA_DESVIADA', 'Mirada desviada'), ('CAMBIO_PESTAÑA', 'Cambio de pestaña'), ('PANTALLA_COMPLETA_OFF', 'Salida de pantalla completa'), ('CONEXION_PERDIDA', 'Conexión perdida'), ('CONEXION_RECUPERADA', 'Conexión recuperada'), ('FIN_SESION', 'Fin de sesión')], max_length=30)),
                ('confianza_algoritmo', models.DecimalField(blank=True, decimal_places=2, help_text='Nivel de confianza del algoritmo (0-100)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('detalles', models.JSONField(blank=True, default=dict, help_text='Detalles técnicos del evento')),
                ('snapshot_url', models.URLField(blank=True, help_text='URL de evidencia (imagen o video)')),
                ('duracion_evento', models.IntegerField(blank=True, help_text='Duración del evento en milisegundos', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Registro de Monitoreo',
                'verbose_name_plural': 'Registros de Monitoreo',
                'db_table': 'registros_monitoreo',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Expulsion',
            fields=[
                ('id_expulsion', models.AutoField(primary_key=True, serialize=False)),
                ('estudiante_id', models.IntegerField(db_index=True)),
                ('estudiante_nombre', models.CharField(max_length=200)),
                ('examen_id', models.IntegerField()),
                ('examen_titulo', models.CharField(max_length=200)),
                ('motivo', models.CharField(choices=[('MAX_ADVERTENCIAS', 'Máximo de advertencias alcanzado'), ('FRAUDE', 'Fraude detectado'), ('VIOLACION_NORMAS', 'Violación de normas'), ('FALLO_TECNICO', 'Fallo técnico'), ('MANUAL', 'Expulsión manual')], max_length=30)),
                ('descripcion', models.TextField()),
                ('advertencias_previas', models.IntegerField(default=0)),
                ('docente_notificado', models.BooleanField(default=False)),
                ('admin_notificado', models.BooleanField(default=False)),
                ('evidencias', models.JSONField(default=list, help_text='Lista de URLs de evidencia')),
                ('calificacion_asignada', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('intento', models.OneToOneField(db_column='intento_id', on_delete=django.db.models.deletion.CASCADE, related_name='expulsion', to='monitoreo.registromonitoreo', to_field='intento_id')),
            ],
            options={
                'verbose_name': 'Expulsión',
                'verbose_name_plural': 'Expulsiones',
                'db_table': 'expulsiones',
                'ordering': ['-fecha'],
            },
        ),
    ]
