# Generated by Django 5.2.10 on 2026-01-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expulsion',
            name='intento',
        ),
        migrations.AddField(
            model_name='expulsion',
            name='intento_id',
            field=models.IntegerField(db_index=True, default=0, help_text='ID del intento expulsado', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registromonitoreo',
            name='intento_id',
            field=models.IntegerField(db_index=True, help_text='ID del intento del examen'),
        ),
        migrations.AddIndex(
            model_name='advertencia',
            index=models.Index(fields=['intento_id', 'fecha'], name='advertencia_intento_7d54da_idx'),
        ),
        migrations.AddIndex(
            model_name='advertencia',
            index=models.Index(fields=['intento_id', 'tipo'], name='advertencia_intento_f36ea1_idx'),
        ),
        migrations.AddIndex(
            model_name='expulsion',
            index=models.Index(fields=['intento_id', 'fecha'], name='expulsiones_intento_26cfd2_idx'),
        ),
        migrations.AddIndex(
            model_name='expulsion',
            index=models.Index(fields=['examen_id', 'fecha'], name='expulsiones_examen__c7db64_idx'),
        ),
        migrations.AddIndex(
            model_name='registromonitoreo',
            index=models.Index(fields=['intento_id', 'timestamp'], name='registros_m_intento_079411_idx'),
        ),
        migrations.AddIndex(
            model_name='registromonitoreo',
            index=models.Index(fields=['intento_id', 'tipo_evento'], name='registros_m_intento_fdd701_idx'),
        ),
    ]
