# Generated by Django 5.2.10 on 2026-02-03 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoreo', '0002_remove_expulsion_intento_expulsion_intento_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertencia',
            name='tipo',
            field=models.CharField(choices=[('AUSENCIA', 'Estudiante no detectado'), ('FUERA_DE_ENCUADRE', 'Estudiante fuera de encuadre'), ('MULTIPLES_PERSONAS', 'Múltiples personas detectadas'), ('MIRADA_DESVIADA', 'Mirada fuera de pantalla'), ('OJOS_CERRADOS', 'Ojos cerrados'), ('OBJETO_NO_AUTORIZADO', 'Objeto no autorizado'), ('CAMBIO_VENTANA', 'Cambio de ventana'), ('PERDIDA_CONEXION', 'Pérdida de conexión'), ('CAMARA_BLOQUEADA', 'Cámara bloqueada'), ('COMPORTAMIENTO_SOSPECHOSO', 'Comportamiento sospechoso')], max_length=30),
        ),
        migrations.AlterField(
            model_name='registromonitoreo',
            name='tipo_evento',
            field=models.CharField(choices=[('INICIO_SESION', 'Inicio de sesión'), ('FRAME_PROCESADO', 'Frame procesado'), ('ROSTRO_DETECTADO', 'Rostro detectado'), ('SIN_ROSTRO', 'Sin rostro detectado'), ('FUERA_DE_ENCUADRE', 'Fuera de encuadre'), ('MULTIPLES_ROSTROS', 'Múltiples rostros detectados'), ('MIRADA_DESVIADA', 'Mirada desviada'), ('OJOS_CERRADOS', 'Ojos cerrados'), ('CAMBIO_PESTAÑA', 'Cambio de pestaña'), ('PANTALLA_COMPLETA_OFF', 'Salida de pantalla completa'), ('CONEXION_PERDIDA', 'Conexión perdida'), ('CONEXION_RECUPERADA', 'Conexión recuperada'), ('FIN_SESION', 'Fin de sesión')], max_length=30),
        ),
    ]
