# Generated by Django 5.2.10 on 2026-01-23 14:46

import Aplicaciones.usuarios.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(db_index=True, max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='La cédula debe tener 10 dígitos', regex='^\\d{10}$')])),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('correo_electronico', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('DOCENTE', 'Docente'), ('ESTUDIANTE', 'Estudiante')], default='ESTUDIANTE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='FotoPerfil',
            fields=[
                ('id_foto', models.AutoField(primary_key=True, serialize=False)),
                ('foto', models.ImageField(upload_to=Aplicaciones.usuarios.models.ruta_foto_usuario)),
                ('foto_validacion', models.ImageField(blank=True, help_text='Foto tomada durante el examen para validación facial', null=True, upload_to='fotos_validacion/')),
                ('embeddings', models.JSONField(blank=True, help_text='Embeddings faciales para reconocimiento', null=True)),
                ('validada', models.BooleanField(default=False)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='foto_perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Foto de Perfil',
                'verbose_name_plural': 'Fotos de Perfil',
                'db_table': 'fotos_perfil',
            },
        ),
        migrations.CreateModel(
            name='SesionUsuario',
            fields=[
                ('id_sesion', models.AutoField(primary_key=True, serialize=False)),
                ('token_hash', models.CharField(db_index=True, max_length=255, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('expira_en', models.DateTimeField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión de Usuario',
                'verbose_name_plural': 'Sesiones de Usuario',
                'db_table': 'sesiones_usuario',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['usuario', 'activo'], name='sesiones_us_usuario_852ecb_idx'), models.Index(fields=['expira_en'], name='sesiones_us_expira__b382bf_idx')],
            },
        ),
    ]
