# Generated by Django 5.2.10 on 2026-01-26 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fotoperfil',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sesionusuario',
            options={'ordering': ['-creado_en']},
        ),
        migrations.RemoveIndex(
            model_name='sesionusuario',
            name='sesiones_us_usuario_852ecb_idx',
        ),
        migrations.RemoveIndex(
            model_name='sesionusuario',
            name='sesiones_us_expira__b382bf_idx',
        ),
        migrations.AlterField(
            model_name='fotoperfil',
            name='embeddings',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fotoperfil',
            name='foto_validacion',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_validacion/'),
        ),
    ]
