# Generated by Django 5.2.10 on 2026-02-04 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_fotoperfil_options_alter_sesionusuario_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesionusuario',
            name='token_hash',
            field=models.CharField(db_index=True, max_length=64, unique=True),
        ),
    ]
